spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev        #开发环境
  application:
    name: tests-config-dev
---
spring:
  profiles: test         #测试环境
  application: 
    name: tests-config-test
#   请保存为UTF-8格式,不能有TAB
